### ISSUE TITLE
Accelerometer unit scaling

### ISSUE THREAD

**Issue by varunm99** [RoboJackets/battlebots-software#14]
Accelerometers on main control board seem to work (we can read the self test and acceleration values) but do not scale to real units. This is probably due to some sort of simple bug with the bitwise math or settings on the accelerometer. Investigate and confirm. 

To confirm result, we should be able to read acceleration in units of Gs and see approximately -1G in z-axis when the accelerometer is sitting on the table.

**Comment by archishou** [comment]
9/1 Noticed inccenistencies in readings of setup registers in a looped setting of 20 milliseconds. Sometimes we got 15 for ADXL375_REG_BW_RATE and others it's 2, 3, 8, or 0.
